### ISSUE TITLE
What devices does sptui need

### ISSUE THREAD

**Issue by 0323pin** [szktkfm/sptui#1]
Hi,

I've packaged and built `sptui` for NetBSD, you can find the work-in-progress package [here](http://mail-index.netbsd.org/pkgsrc-wip-changes/2024/01/18/msg029222.html).

Now, launching the TUI and selecting a song outputs the following (see screenshot) but **:play** doesn't do anything.
![2024-01-18-153410_1366x768_scrot](https://github.com/szktkfm/sptui/assets/90570748/bb24f722-2af1-4130-beec-7398a8276807)

Is this like `gospt`, https://git.asdf.cafe/abs3nt/gospt/ not really a Spotify client but, more of a client controller and I actually need a client like `librespot` or, `spotifyd` running in the background?

Now, I do use [spotify-player](https://github.com/aome510/spotify-player) and maybe that is the _active device found_.

Thank you for any hints.

**Comment by 0323pin** [comment]
Guess I found the answer to my question elsewhere, https://www.reddit.com/r/commandline/comments/1984eit/sptui_a_spotify_tui_player_written_in_go_and/

**Comment by szktkfm** [comment]
@0323pin 
sptui need a daemon like spotifyd running in the background for it to work properly.

**Comment by 0323pin** [comment]
> @0323pin sptui need a daemon like spotifyd running in the background for it to work properly.

Yes, I got that from the reddit discussion but, forgot to close the issue.

In this case, the package is ready to be merged. I'll try to push it into the main branch in the next couple of days.
