### ISSUE TITLE
What tool is used to generate the gif?

### ISSUE THREAD

**Issue by kitesi** [szktkfm/sptui#3]
Hi, I wanted to know what tool is being used to generate the gif which seems to be automated from `assets/sptui.tape`

I have looked into asciinema and ttyrec, but they do not seem to be it.

**Comment by szktkfm** [comment]
The tool used is `vhs`. You can find more details at: https://github.com/charmbracelet/vhs.

**Comment by kitesi** [comment]
Perfect, thank you.
